### ISSUE TITLE
Cloning a ModuleInstance ?

### ISSUE THREAD

**Issue by sletz** [AndrewScheidecker/WAVM#58]
In our use case (Using WAVM as a target for the Faust compiler), we typically need to create several **ModuleInstance** from a given **Module**. I don't find an explicit ModuleInstance clone method. Should we load the Module again and again and create new  'ModuleInstances' from there ? (so using the instantiateModule) , or is there a way to load/create the given Module once and create several instances from it?

**Comment by AndrewScheidecker** [comment]
You should be able to call `instantiateModule` multiple times for the same module. It will compile the module's code again for each instance, but it should work. The reason is that right now things like the memory, table, imported function, and global addresses are baked into the machine code, so you can't rebind those imports without generating a new version of the machine code. Adding a function to clone the module instance would have to do something very similar to what `instantiateModule` already does.

**Comment by sletz** [comment]
It worked thanks !
