### ISSUE TITLE
Trouble using external functions

### ISSUE THREAD

**Issue by sletz** [AndrewScheidecker/WAVM#82]
My Faust generated module uses some math functions, it has the following kind of import:

```
....
(import "env" "_expf" (func $fimport$0 (param f32) (result f32)))
(import "env" "_powf" (func $fimport$1 (param f32 f32) (result f32)))
(import "env" "_tanf" (func $fimport$2 (param f32) (result f32)))
.... 
```

With older version of WAVM, to add the external functions, I was doing:

```
.....
DEFINE_INTRINSIC_FUNCTION1(env,_expf,_expf,f32,f32,value) { return std::exp(value); }
.....
```
With the current version I changed the code to:

```
DEFINE_INTRINSIC_MODULE(env)
DEFINE_INTRINSIC_FUNCTION(env,"_expf",F32,_expf,F32 value) { return std::exp(value); }
...
```

But I get the following kind of error at runtime and the programs crashes:

`Generated stub for missing import env._expf : func (f32)->f32`

Any idea of what is still wrong? Thanks.

**Comment by AndrewScheidecker** [comment]
In the latest code, intrinsic modules need to be explicitly instantiated and linked with the module to be executed. For example, see how [the ThreadTest module is linked](https://github.com/AndrewScheidecker/WAVM/blob/master/Source/Programs/wavm.cpp#L144).

The easiest solution would be to put these functions in `Emscripten.cpp`, in particular if you can't change that they are imported from "env". Otherwise, I'd call your intrinsic module something different, and hook it up the same way that ThreadTest is.

**Comment by sletz** [comment]
My generated does not use Emscripten, I am just using the same "env" naming. I've just added the following line at the right place:

` moduleNameToInstanceMap["env"] = Intrinsics::instantiateModule(compartment,INTRINSIC_MODULE_REF(env));`

And now it works again, thanks a lot !
